Repository silagokth/vesyla, pull requests merged in 2025-05, with the labels that each got.

#62 feat: support for new drra-components folder structure
  module/vs-component/Cargo.toml
  module/vs-component/src/utils.rs
Labels: bug, documentation, feature, changelog:feature

#66 change all version to 4.2.0, remove subcommand version
  module/vs-entry/Cargo.toml
  module/vs-entry/src/main.rs
  module/vs-manas/Cargo.lock
  module/vs-manas/Cargo.toml
  module/vs-testcase/Cargo.toml
Labels: changelog:skip

#67 Hotfix 4.2.1
  .github/workflows/ci-draft-release.yml
  module/vs-component/Cargo.toml
Labels: bug

#72 feat: integrate auto versioning for all modules
  modules/Cargo.lock
  modules/Cargo.toml
  modules/build-utils/Cargo.toml
  modules/build-utils/src/lib.rs
  modules/build.rs
  modules/src/main.rs
  modules/vs-component/Cargo.toml
  modules/vs-component/build.rs
  modules/vs-component/src/main.rs
  modules/vs-manas/Cargo.toml
  modules/vs-manas/build.rs
  modules/vs-manas/src/main.rs
  modules/vs-schedule/.gitignore
  modules/vs-schedule/CMakeLists.txt
  modules/vs-schedule/src/main.py
  modules/vs-testcase/Cargo.toml
  modules/vs-testcase/build.rs
  modules/vs-testcase/src/main.rs
Labels: changelog:feature

#82 feat: Add Makefile for Standardized Build and Install
  Makefile
  README.md
Labels: feature, changelog:feature
