Repository silagokth/vesyla, pull requests merged in 2025-06, with the labels that each got.

#95 fix bug #93, #94, and make BinaryTree template
  modules/vs-compile/src/exec/main.cpp
  modules/vs-compile/src/schedule/Scheduler.cpp
  modules/vs-compile/src/tm/BinaryTree.cpp
  modules/vs-compile/src/tm/BinaryTree.hpp
  modules/vs-compile/src/tm/TimingModel.cpp
  modules/vs-compile/src/tm/TimingModel.hpp
  modules/vs-compile/src/util/Common.hpp
  modules/vs-compile/src/util/GlobalVar.cpp
  modules/vs-compile/src/util/GlobalVar.hpp
  modules/vs-compile/src/util/RandName.cpp
  modules/vs-compile/src/util/RandName.hpp
  modules/vs-compile/src/util/SysPath.cpp
  modules/vs-compile/src/util/SysPath.hpp
  modules/vs-testcase/assets/autotest_template.robot.jinja
  modules/vs-testcase/src/main.rs
Labels: bug, changelog:bugfix

#98 feat(vs-compile): add mlir-lsp-server support for PASM dialect
  modules/vs-compile/CMakeLists.txt
  modules/vs-compile/src/util/mlir_lsp_support/README.md
  modules/vs-compile/src/util/mlir_lsp_support/lsp_server.cpp
Labels: feature, changelog:feature

#99 Chore: replace deprecated mlir function
  README.md
  modules/vs-compile/CMakeLists.txt
  modules/vs-compile/src/exec/pasm-mlir-lsp-server/README.md
  modules/vs-compile/src/exec/pasm-mlir-lsp-server/main.cpp
  modules/vs-compile/src/exec/vs-compile/main.cpp
  modules/vs-compile/src/pasm/AddDefaultValuePass.cpp
  modules/vs-compile/src/pasm/AddHaltPass.cpp
  modules/vs-compile/src/pasm/AddSlotPortPass.cpp
  modules/vs-compile/src/pasm/Dialect.cpp
  modules/vs-compile/src/pasm/Dialect.hpp
  modules/vs-compile/src/pasm/Dialect.td
  modules/vs-compile/src/pasm/MergeRawOp.cpp
  modules/vs-compile/src/pasm/Ops.hpp
  modules/vs-compile/src/pasm/Ops.td
  modules/vs-compile/src/pasm/Passes.cpp
  modules/vs-compile/src/pasm/Passes.hpp
  modules/vs-compile/src/pasm/Passes.td
  modules/vs-compile/src/pasm/ScheduleEpochPass.cpp
  modules/vs-compile/src/pasm/Types.hpp
  modules/vs-compile/src/pasm/Types.td
  modules/vs-compile/src/schedule/BisonUtil.cpp
  modules/vs-compile/src/schedule/BisonUtil.hpp
  modules/vs-compile/src/schedule/FlexUtil.cpp
  modules/vs-compile/src/schedule/FlexUtil.hpp
  modules/vs-compile/src/schedule/GlobalUtil.cpp
  modules/vs-compile/src/schedule/GlobalUtil.hpp
  modules/vs-compile/src/schedule/Parser.hpp
  modules/vs-compile/src/schedule/flex_util.hpp
  modules/vs-compile/src/schedule/pasm.l
  modules/vs-compile/src/schedule/pasm.y
  scripts/make_appimage.sh
Labels: changelog:bugfix
